version: '3.7'

services:
  nodered:
    image: nodered/node-red:3.0.2-18
    # network_mode: host
    extra_hosts:
      - 'api.yousolution.local:192.168.1.100'
    volumes:
      - ./data:/data
    ports:
      - '1880:1880'

    deploy:
      resources:
        limits:
          # cpus: 0.50
          memory: 45M

    environment:
      NODE_ENV: 'dev'
      NODE_OPTIONS: '--max-old-space-size=40'
